### ISSUE TITLE
Install via HomeAssistant no longer possible

### ISSUE THREAD

**Issue by ChristianLoacker** [milanmeu/aioaseko#7]
Hi - again.

I have tried to install the latest version on the following system:

Home Assistant 2023.8.4 
Supervisor 2023.08.1 
Operating System 10.5 
Frontend 20230802.1 - latest 

After entering Username and Password I get the Error Message with no further details. Simply no connection possible. Tried with two different Aseko accounts on the Homeassistant above and on a container version Home Assistant Core 2022.5.0b6

Didn't work at all. Tried on the weekend and today again. Looks like the integration doesn't even connect any more when installed new.

Hope that it finally works again for all of us as soon as possible!

Christian

**Comment by hopkins-tk** [comment]
We have fixed the part in this project - covered by https://github.com/milanmeu/aioaseko/issues/1
The HomeAssistant counter part of the change is here: https://github.com/home-assistant/core/pull/99495
